### ISSUE TITLE
How go from EEGLAB regular SET files to the files plot_erp needs?

### ISSUE THREAD

**Issue by RenzoLanfranco** [lrkrol/plot_erp#2]
Hi. I really like the plotting style of this script - the plots look very clear, especially the first one. However, the script requires the data to be structured in a way that I've never used before. Normally, in EEGLAB you get one SET file per participant, which contains triggers for each condition. Sometimes one condition can encompass several triggers. However, it seems that this script requires the data to be structured in a cumbersome way: a SET file (I assume... it doesn't say) per subject x condition. Is that so? Can one simply use data structured in a more standard way (one SET file per participant containing all the EEG triggers)? Or is there a quick way to take those SET files and turn them into the files this script needs?

Thank you!

**Comment by lrkrol** [comment]
Hey Renzo, you are right that this script only takes already-epoched datasets, in EEGLAB format. This script is only for plotting: all pre-processing should be done beforehand, including the epoching itself. How you epoch is up to you; it doesn't necessarily have to correspond to a "condition" in every possible understanding of the word.

When you have a continuous dataset in EEGLAB that contains multiple triggers, you should first preprocess this data however you want to (e.g. filtering, re-referencing, etc.), and then transform this dataset into epochs depending on how you want to plot the data. [Here is the EEGLAB tutorial on epoching.](https://sccn.ucsd.edu/wiki/I.5:_Extracting_Data_Epochs)

For example, if for one participant you want to compare the ERP for `trigger1` versus `trigger2`, you could epoch this participant's continuous dataset `EEG` into two epoched datasets as follows:

```
EEGtrigger1 = pop_epoch(EEG, {'trigger1'}, [-1 2]);
EEGtrigger2 = pop_epoch(EEG, {'trigger2'}, [-1 2]);

EEGtrigger1 = pop_rmbase(EEGtrigger1, [-1000 0]);
EEGtrigger2 = pop_rmbase(EEGtrigger2, [-1000 0]);
```

The two resulting, epoched datasets can then be plotted as per the README of this repo (e.g. `plot_erp({EEGtrigger1, EEGtrigger2}, 'Fz');`. 

`pop_epoch` also allows you to extract multiple triggers into one dataset. Once you have the epoched datasets you want, `plot_erp` can help with plotting them.
