### ISSUE TITLE
Issue with the input data format

### ISSUE THREAD

**Issue by saeidehdavoudi** [lrkrol/plot_erp#3]
Hello,

I have trouble with the epoch format. My dataset is epoched and I have EEG.data format as channel*time*trial. How can I transformed it to be used in plot_erp? (I want to plot two types of erps (two conditions) in one subject)

Thank you in advance

Saeideh

**Comment by lrkrol** [comment]
Salam Saeideh,

A dataset epoched using EEGLAB should automatically have the correct format, and that should indeed be channels\*samples\*trials, so no transformation should be necessary.

When comparing two conditions in one subject, you would create two separate epoched datasets, one for each condition, and plot them e.g. like `plot_erp({EEGcondition1, EEGcondition2}, 'Fz');`, with EEGcondition1/2 being those two epoched datasets.

If that is what you're doing but it's not working, please show me a short script so I can try and figure out what's happening.

All the best,

Laurens

**Comment by saeidehdavoudi** [comment]
> Salam Saeideh,
> 
> A dataset epoched using EEGLAB should automatically have the correct format, and that should indeed be channels*samples*trials, so no transformation should be necessary.
> 
> When comparing two conditions in one subject, you would create two separate epoched datasets, one for each condition, and plot them e.g. like `plot_erp({EEGcondition1, EEGcondition2}, 'Fz');`, with EEGcondition1/2 being those two epoched datasets.
> 
> If that is what you're doing but it's not working, please show me a short script so I can try and figure out what's happening.
> 
> All the best,
> 
> Laurens

**Comment by saeidehdavoudi** [comment]
Hello (Salam) Laurens,

Thank you so much for your prompt reply.
It was my mistake. I had put EEG.data as epoch since it requires the structure.

Best regards,

Saeideh
